namespace MaplibreNative.Routing.Core.Models;

/// <summary>Valhalla maneuver type values used for highway detection and step rendering.
/// Ported from maplibre-navigation-android / Valhalla API docs.</summary>
public enum ManeuverType
{
    None = 0,
    Start = 1,
    StartRight = 2,
    StartLeft = 3,
    Destination = 4,
    DestinationRight = 5,
    DestinationLeft = 6,
    Becomes = 7,
    Continue = 8,
    SlightRight = 9,
    Right = 10,
    SharpRight = 11,
    UturnRight = 12,
    UturnLeft = 13,
    SharpLeft = 14,
    Left = 15,
    SlightLeft = 16,
    RampStraight = 17,
    RampRight = 18,
    RampLeft = 19,
    ExitRight = 20,
    ExitLeft = 21,
    StayStraight = 22,
    StayRight = 23,
    StayLeft = 24,
    Merge = 25,
    RoundaboutEnter = 26,
    RoundaboutExit = 27,
    FerryEnter = 28,
    FerryExit = 29,
    Transit = 30,
    TransitTransfer = 31,
    TransitRemainOn = 32,
    TransitConnectionStart = 33,
    TransitConnectionTransfer = 34,
    TransitConnectionDestination = 35,
    PostTransitConnectionDestination = 36,
    MergeRight = 37,
    MergeLeft = 38,
    ElevatorEnter = 39,
    StepsEnter = 40,
    EscalatorEnter = 41,
    BuildingEnter = 42,
    BuildingExit = 43,
}
